//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMVVMAgendaEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefoane
    {
        public int idTelefon { get; set; }
        public int idPersoana { get; set; }
        public string numarTelefon { get; set; }
        public string descriere { get; set; }
    
        public virtual persoane persoane { get; set; }
    }
}
