//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMVVMAgendaEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persoane
    {
        public persoane()
        {
            this.telefoanes = new HashSet<telefoane>();
        }
    
        public int idPersoana { get; set; }
        public string nume { get; set; }
        public string adresa { get; set; }
    
        public virtual ICollection<telefoane> telefoanes { get; set; }
    }
}
